[[redirects]]
  from = "/stores/*"
  to = "https://jlvadtrbkq.us16.qoddiapp.com/stores/:splat"  
  status = 200
  force = true

[[redirects]]
  from = "/users/*"
  to = "https://jlvadtrbkq.us16.qoddiapp.com/users/:splat"  
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200